Update test-prod-tracks-new.yml

diff --git a/.github/workflows/test-prod-tracks-new.yml b/.github/workflows/test-prod-tracks-new.yml
--- a/.github/workflows/test-prod-tracks-new.yml
+++ b/.github/workflows/test-prod-tracks-new.yml
@@ -22,7 +22,7 @@ jobs:
       env:
         INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_API_KEY }}
         
-    - name: get production tracks
+    - name: test production tracks
       run: |
         tracks="$(\
         curl https://play.instruqt.com/graphql \
@@ -30,19 +30,31 @@ jobs:
         -H "Accept: application/json" \
         -H "Authorization: Bearer $INSTRUQT_API_KEY" \
         -d '{"query":"query tracks {\n  tracks(organizationSlug: \"redhat\") {\n    slug\n    maintenance\n  }\n}\n","variables":{}}' --compressed | jq -s '.[].data.tracks[] | select(.maintenance==false) | .slug' | jq -R -s -c 'split("\n")[:-1]' | sed 's/\\//g' | sed 's/\"\"/"/g'\
-        )" >> $GITHUB_ENV
+        )"
+        for i in "${tracks[@]}"
+        do
+          testtrack="$(/usr/local/bin/instruqt track test $INSTRUQT_ORG/$i)"
+          if [ $? -eq 0 ]
+          then
+            echo "::group::Track test"
+            echo "$testtrack"
+            echo "::endgroup"
+            echo "$i" >> $GITHUB_STEP_SUMMARY
+            echo "no errors\n" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          elif [ $? -eq 1 ]
+          then
+            echo "::group::Track test"
+            echo "$testtrack"
+            echo "::endgroup::"
+            error="$(echo "$testtrack" | grep "ERROR")"
+            echo "$i" >> $GITHUB_STEP_SUMMARY
+            echo "$error" >> $GITHUB_STEP_SUMMARY
+            sleep 2
+            exit 1
+          fi
+        done
       env:
         INSTRUQT_API_KEY: ${{ secrets.INSTRUQT_API_KEY }}
         INSTRUQT_ORG: ${{ secrets.INSTRUQT_ORG }}
-      
-    - name: test tracks
-      shell: bash {0}
-      run: |
-        for i in "${!tracks[@]}"
-        do
-          echo "$i"
-        done
-      env:
         INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_API_KEY }}
-        INSTRUQT_ORG: ${{ secrets.INSTRUQT_ORG }}
-        tracks: env.tracks
